#!/bin/bash
#Prints amount of free memory on the system and saves it to file
free -h | tee -a ~/backups/freemem/free_mem.txt &&
#Prints disk usage and saves it to file
df -h | tee -a ~/backups/diskuse/disk_usage.txt &&
#Lists all open files and saves to file
lsof >> ~/backups/openlist/open_list.txt &&
#Prints file system disk space statistics and saves it to file
du -h | tee -a ~/backups/freedisk/free_disk.txt
